name: Security Review

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - '**.tf'
      - '**.yaml'
      - '**.yml'

jobs:
  security-review:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      statuses: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install checkov
          
      - name: Run security review
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          AUTO_FIX_ENABLED: 'true'
          MIN_SEVERITY_LEVEL: 'LOW'
        run: |
          uvicorn app.main:app --host 0.0.0.0 --port 8000 &
          sleep 5  # Wait for server to start
          
          # Trigger review via API
          curl -X POST http://localhost:8000/webhook/github \
            -H "Content-Type: application/json" \
            -H "X-GitHub-Event: pull_request" \
            -d '{
              "action": "${{ github.event.action }}",
              "pull_request": ${{ toJSON(github.event.pull_request) }}
            }' 